# Production configuration for FastAPI application

# Application configuration
app:
  name: fastapi-app
  namespace: fastapi-helm-prod

# Backend configuration
backend:
  name: backend
  image: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app/backend
  tag: 0.6.0
  port: 8000
  replicas: 2
  service:
    type: ClusterIP
    port: 80

# Frontend configuration
frontend:
  name: frontend
  image: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app/frontend
  tag: 0.6.0
  port: 80
  replicas: 2
  service:
    type: ClusterIP
    port: 80

# ConfigMap values for production
configMap:
  allowedOrigins: https://dashboard.example.com
  corsSettings: "true"
  debugMode: "false"
  # Use secretRef for database URL
  databaseUrlSecret:
    name: fastapi-prod-secrets
    key: DATABASE_URL
  # Use secretRef for application secret key
  secretKeyRef:
    name: fastapi-prod-secrets
    key: APP_SECRET_KEY

# Production security context
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Resource limits for production
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Autoscaling configuration for production
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls
      hosts:
        - api.example.com

# Image pull secrets for private registry
imagePullSecrets:
  - name: ghcr-secret

# Health check probes
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
