aws:
  s3_endpoint: http://localstack:4566
  sqs_endpoint: http://localstack:4566
  sns_endpoint: http://localstack:4566
  region: us-east-1
  access_key_id: test
  secret_access_key: test
image:
  tag: latest