# Values for playground environment
app:
  name: fastapi-app
  namespace: fastapi-helm-playground

# Backend configuration
backend:
  name: backend
  image: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app/backend
  tag: pr-latest  # This will be updated by the CI pipeline with PR-specific tag
  replicas: 1
  port: 8000
  service:
    name: backend-service
    port: 8000
    type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Frontend configuration
frontend:
  name: frontend
  image: ghcr.io/datascientest-fastapi-project-group-25/fastapi-project-app/frontend
  tag: pr-latest  # This will be updated by the CI pipeline with PR-specific tag
  replicas: 1
  port: 80
  service:
    name: frontend-service
    port: 80
    type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Database configuration
database:
  name: postgres
  image: postgres
  tag: "12"
  storage:
    size: 1Gi
  credentials:
    username: postgres
    password: postgres
    database: postgres
  service:
    name: postgres
    port: 5432
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: playground.example.com  # This would be replaced with actual domain

# ConfigMap values
configMap:
  databaseUrl: "postgresql://postgres:postgres@postgres:5432/postgres"
  allowedOrigins: "*"
  corsSettings: "true"
  debugMode: "true"
  secretKey: "playground-secret-key"

# Security context
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false  # Set to false for easier debugging
  runAsNonRoot: true
  runAsUser: 1000
