apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  # Environment settings
  ENVIRONMENT: "{{ .Values.app.environment }}"
  PROJECT_NAME: "FastAPI"
  
  # Domain settings
  DOMAIN: "localhost"
  FRONTEND_HOST: "http://{{ .Values.frontend.service.name }}:{{ .Values.frontend.service.port }}"
  SERVER_HOST: "http://{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}"
  
  # CORS settings
  BACKEND_CORS_ORIGINS: '{{ .Values.configMap.allowedOrigins | default "*" | quote }}'
  
  # Postgres settings
  POSTGRES_USER: "{{ .Values.database.credentials.username }}"
  POSTGRES_DB: "{{ .Values.database.credentials.database }}"
  POSTGRES_SERVER: "{{ .Values.database.service.name }}"
  POSTGRES_PORT: "{{ .Values.database.service.port }}"
  
  # Database URL
  DATABASE_URL: "postgresql://{{ .Values.database.credentials.username }}:{{ .Values.database.credentials.password }}@{{ .Values.database.service.name }}:{{ .Values.database.service.port }}/{{ .Values.database.credentials.database }}"
  
  # User settings
  FIRST_SUPERUSER: "admin@example.com"
  
  # Debug settings
  DEBUG: "{{ .Values.configMap.debug | default "false" }}"
