apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  # Environment settings
  ENVIRONMENT: "local"
  PROJECT_NAME: "FastAPI"
  
  # Domain settings
  DOMAIN: "localhost"
  FRONTEND_HOST: "http://{{ .Values.frontend.service.name }}:{{ .Values.frontend.service.port }}"
  SERVER_HOST: "http://{{ .Values.backend.service.name }}:{{ .Values.backend.service.port }}"
  
  # CORS settings
  BACKEND_CORS_ORIGINS: '{{ .Values.configMap.allowedOrigins | quote }}'
  
  # Postgres settings
  POSTGRES_USER: "{{ .Values.database.credentials.username }}"
  POSTGRES_SERVER: "{{ .Values.database.service.name }}"
  POSTGRES_PORT: "{{ .Values.database.service.port }}"
  POSTGRES_DB: "{{ .Values.database.credentials.database }}"
  
  # User settings
  FIRST_SUPERUSER: "admin@example.com"
  
  # Backend settings
  VITE_API_URL: "http://{{ .Values.ingress.host }}/api"
  
  # Email settings
  SMTP_USER: "smtp-user"
  SMTP_HOST: "smtp.gmail.com"
  EMAILS_FROM_EMAIL: "info@example.com"
  
  # Database URL
  DATABASE_URL: "{{ .Values.configMap.databaseUrl }}"
