apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.credentials.password | b64enc }}
  SECRET_KEY: {{ .Values.configMap.secretKey | b64enc }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.configMap.firstSuperuserPassword | b64enc }}
  SMTP_PASSWORD: c210cC1wYXNz # "smtp-pass" in base64
  SENTRY_DSN: "" # Add your Sentry DSN here
