apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                {{- if .Values.configMap.databaseUrlSecret }}
                secretKeyRef:
                  name: {{ .Values.configMap.databaseUrlSecret.name }}
                  key: {{ .Values.configMap.databaseUrlSecret.key }}
                {{- else }}
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: databaseUrl
                {{- end }}
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: allowedOrigins
            - name: CORS_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: corsSettings
            - name: DEBUG_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: debugMode
            - name: SECRET_KEY
              valueFrom:
                {{- if .Values.configMap.secretKeyRef }}
                secretKeyRef:
                  name: {{ .Values.configMap.secretKeyRef.name }}
                  key: {{ .Values.configMap.secretKeyRef.key }}
                {{- else }}
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: secretKey
                {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      podSecurityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}