apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  databaseUrl: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  secretKey: {{ .Values.secrets.secretKey | b64enc | quote }}