apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/datascientest-fastapi-project-group-25/fastAPI-project-release.git
    targetRevision: automation  # The branch that will be monitored
    path: fastapi-helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-stg # Standardized name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/datascientest-fastapi-project-group-25/fastAPI-project-release.git
    targetRevision: HEAD # Align with application-stg.yaml, assuming changes are merged to main/HEAD
    path: charts/fastapi # Align with application-stg.yaml path
    helm:
      valueFiles:
        - ../../config/helm/values-stg.yaml # Align with application-stg.yaml value file path
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-stg # Align with application-stg.yaml namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true