name: PR Checks
# This workflow runs checks on pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
permissions:
  contents: read
  pull-requests: write
jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Helm tests
        run: make lint
  test-argocd-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate ArgoCD configs
        run: |
          # Your ArgoCD validation steps from helm-argocd-test.yml
  test-deployment:
    needs: [validate-helm, test-argocd-config]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      # Skip setup-k3d step as it requires Docker-in-Docker, which is not available in GitHub Actions
      # - name: Set up test environment
      #   run: make setup-k3d
      - name: Deploy and test
        run: make template-staging
