apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/datascientest-fastapi-project-group-25/fastAPI-project-release.git
    targetRevision: stg  # The staging branch
    path: charts/fastapi
    helm:
      valueFiles:
        - ../../config/helm/staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-helm-staging
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources that are no longer defined in Git
      selfHeal: true  # Automatically sync resources that differ from Git state
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground  # Wait for dependent resources to be deleted
      - PruneLast=true  # Delete resources only after new ones are healthy
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore differences in replica count (managed by HPA)
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status  # Ignore HPA status differences