apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-db
        image: tybaloo/backend:latest
        command: ['python3']
        args: ['-c', 'import alembic.config; import os; os.chdir("/app"); alembic.config.main(argv=["upgrade", "head"])']
        envFrom:
        - configMapRef:
            name: fastapi-config
        - secretRef:
            name: fastapi-secret
      containers:
      - name: backend
        image: tybaloo/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: fastapi-config
        - secretRef:
            name: fastapi-secret
        livenessProbe:
          httpGet:
            path: /api/v1/utils/health-check/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10