apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: fastapi-app
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # "password" in base64
  SECRET_KEY: c3VwZXJzZWNyZXQ= # "supersecret" in base64
  FIRST_SUPERUSER_PASSWORD: c3VwZXJwYXNz # "superpass" in base64
  SMTP_PASSWORD: c210cC1wYXNz # "smtp-pass" in base64
  SENTRY_DSN: "" # Add your Sentry DSN here
