# Release (staging) environment configuration
app:
  namespace: fastapi-helm-release
  environment: release

backend:
  name: backend
  image: tybaloo/backend
  tag: latest
  replicas: 1  # Single replica for staging
  port: 8000
  resources:
    requests:
      memory: "192Mi"
      cpu: "150m"
    limits:
      memory: "384Mi"
      cpu: "400m"
  # Release environment settings
  args:
    - "app.main:app"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8000"
    - "--workers"
    - "2"  # More workers than dev, fewer than prod
    - "--log-level"
    - "info"  # Less verbose than debug
  service:
    name: backend-service
    port: 8000
    type: ClusterIP

frontend:
  name: frontend
  image: tybaloo/frontend
  tag: latest
  replicas: 1
  port: 80
  resources:
    requests:
      memory: "96Mi"
      cpu: "75m"
    limits:
      memory: "192Mi"
      cpu: "150m"
  service:
    name: frontend-service
    port: 80
    type: ClusterIP

database:
  name: postgres
  image: postgres
  tag: "12"  # Use PostgreSQL 12 to match existing data
  service:
    name: postgres
    port: 5432
  credentials:
    username: postgres
    password: postgres
    database: postgres
  storage:
    size: 5Gi  # Medium size for staging
  resources:
    requests:
      memory: "384Mi"
      cpu: "150m"
    limits:
      memory: "768Mi"
      cpu: "400m"

# ConfigMap settings
configMap:
  allowedOrigins: "http://localhost:5174,http://localhost:8002,http://staging.yourdomain.com"
  corsSettings: true
  databaseUrl: "postgresql://postgres:postgres@postgres:5432/postgres"
  debugMode: false
  secretKey: "your-secret-key"
  firstSuperuserPassword: "superpass"

# Release-specific configuration
ingress:
  enabled: false  # Typically use port-forwarding in staging
