# Production environment configuration
app:
  namespace: fastapi-helm-prod
  environment: production

backend:
  name: backend
  image: tybaloo/backend
  tag: latest
  replicas: 2  # Multiple replicas for high availability
  port: 8000
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  # Production environment settings - temporarily using debug mode
  args:
    - "app.main:app"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8000"
    - "--workers"
    - "1"  # Single worker for debugging
    - "--log-level"
    - "debug"  # Debug level for more information
  service:
    name: backend-service
    port: 8000
    type: ClusterIP

frontend:
  name: frontend
  image: tybaloo/frontend
  tag: latest
  replicas: 2  # Multiple replicas for high availability
  port: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  service:
    name: frontend-service
    port: 80
    type: ClusterIP

database:
  name: postgres
  image: postgres
  tag: "12"
  service:
    name: postgres
    port: 5432
  credentials:
    username: postgres
    password: postgres
    database: postgres
  storage:
    size: 10Gi  # Larger size for production
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Production-specific configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: backend-service
          servicePort: 8000
    - host: app.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 80
  tls:
    - secretName: api-tls
      hosts:
        - api.yourdomain.com
    - secretName: app-tls
      hosts:
        - app.yourdomain.com

# ConfigMap values
configMap:
  secretKey: "your-production-secret-key"
  allowedOrigins: "https://app.yourdomain.com,https://api.yourdomain.com"
  debug: "false"
  firstSuperuserPassword: "production-superpass"
