name: PR Creation
on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
permissions:
  contents: write
  pull-requests: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.ref, 'main') && !contains(github.ref, 'master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for existing PR
        id: check-pr
        uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.ref.replace
              ('refs/heads/', '')}`,
              state: 'open'
            });
            return prs.data.length > 0;
      - name: Create Pull Request
        id: create-pr
        if: steps.check-pr.outputs.result == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR from ${{ github.ref_name }}"
          title: "[${{ github.ref_name }}] Automated PR"
          body: |
            ## Automated Pull Request
            This PR was automatically created from branch `${{
            github.ref_name }}`.
            ### Changes
            ${{ github.event.head_commit.message }}
            ### Checklist
            - [ ] Tests have been added/updated
            - [ ] Documentation has been updated
            - [ ] Changes have been reviewed
          base: main
          branch: ${{ github.ref_name }}
          draft: false