apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-prod-secrets
  namespace: fastapi-helm-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: fastapi-prod-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: prod/postgres/credentials # Standardized path
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/postgres/credentials # Standardized path
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod/postgres/credentials # Standardized path
        property: database
    - secretKey: APP_SECRET_KEY
      remoteRef:
        key: prod/app/secrets # Standardized path
        property: secretKey